# Generated by Django 5.1.1 on 2024-10-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='files',
        ),
        migrations.AddField(
            model_name='customuser',
            name='files',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
