# Generated by Django 5.1.1 on 2024-10-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_storage_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='storage_path',
        ),
    ]
