# Generated by Django 5.1.1 on 2024-10-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_storage_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
